### PR TITLE
Reproducible audits

### PR DESCRIPTION
**Pull request by JacobALussier**
Code and tests for the reproducible audits class.

### CODE REVIEW

**Review by JAL-99 — APPROVED** [review]

**Review by brownsarahm — CHANGES_REQUESTED** [review]
Could you remove the untitled notebooks and the test csv  and text.txt files?

**Comment by Shine226** [comment]
@JacobALussier @brownsarahm Do we need to merge 07_reproducible_audits.ipynb? Seems nothing useful in it.

**Comment by Shine226** [comment]
Why there exist tests/.ipynb_checkpoints/Untitled-checkpoint.ipynb and tests/.ipynb_checkpoints/Untitled1-checkpoint.ipynb?

**Comment by brownsarahm** [comment]
@JacobALussier will you be able to make the requested changes?

**Pull request merged**
